using BiscuitOS.Apps.TextEditor;
using BiscuitOS.FileExecutable;
using System.IO;

namespace BiscuitOS.FileExplorer
{
    public class FileMan
    {
        static string CurrentDir = @"0:\";

        public static void ParseFileCommand(string[] commandWord)
        {
            if (commandWord[1] == "new")
            {
                // They want to create a new file
                if (commandWord[2] == "fl" || commandWord[2] == "file")
                {

                    if (commandWord[3] != "")
                    {
                        string[] defText =
                        {
                            "File auto generated by BiscuitOS",
                        };
                        if (isRelative(commandWord[3]))
                        {
                            try
                            {
                                File.Create(GetPath() + commandWord[3]);
                                File.WriteAllLines(GetPath() + commandWord[3], defText);
                            }
                            catch
                            {
                                BError.SystemIOError();
                            }
                        }
                        else
                        {

                            try
                            {
                                File.Create(commandWord[3]);
                                File.WriteAllLines(commandWord[3], defText);
                            }
                            catch
                            {
                                BError.SystemIOError();
                            }
                        }
                    }
                    else
                    {
                        BConsole.WriteLine("Please specify a name for the file.");
                    }

                    if (commandWord[4] == "-r")
                    {
                        if (isRelative(commandWord[3]))
                        {
                            string[] args = { GetPath() + commandWord[3] };
                            TextEditor.StartTextEditor(args);
                        }
                        else
                        {
                            string[] args = { commandWord[3] };
                            TextEditor.StartTextEditor(args);
                        }
                    }
                }else if (commandWord[2] == "dir" || commandWord[2] == "directory")
                {
                    if (isRelative(commandWord[3]))
                    {
                        try
                        {
                            Directory.CreateDirectory(GetPath() + commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }
                    else
                    {
                        try
                        {
                            Directory.CreateDirectory(commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }

                    if (commandWord[4] == "-r")
                    {
                        // Open To Directory
                        if (isRelative(commandWord[3]))
                        {
                            CurrentDir = GetPath() + commandWord[3];
                        }
                        else
                        {
                            CurrentDir = commandWord[3];
                        }
                    }
                }
                else
                {
                    BConsole.WriteLine("Incorrect use of command word 'new'");
                }
            }else if (commandWord[1] == "st")
            {
                // Set text
                try
                {
                    File.WriteAllText(CurrentDir + commandWord[2], commandWord[3]);
                }
                catch
                {
                    BConsole.WriteLine("Failed to write to file");
                }
            }else if (commandWord[1] == "del")
            {
                if (commandWord[2] == "fl" || commandWord[2] == "file")
                {
                    if (isRelative(commandWord[3]))
                    {
                        try
                        {
                            File.Delete(GetPath() + commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }
                    else
                    {
                        try
                        {
                            File.Delete(commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }
                }else if (commandWord[2] == "dir" || commandWord[2] == "directory")
                {
                    if (isRelative(commandWord[3]))
                    {
                        try
                        {
                            Directory.Delete(GetPath() + commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }
                    else
                    {
                        try
                        {
                            Directory.Delete(commandWord[3]);
                        }
                        catch
                        {
                            BError.SystemIOError();
                        }
                    }
                }
            }else if (commandWord[1] == "run")
            {
                FMFile fmFile = new FMFile();
                fmFile.RunFile(GetPath() + commandWord[2]);
            }
            else
            {
                BConsole.WriteLine("Incorrect use of command word 'fm'");
            }
        }

        public static void AddDir(string folder)
        {
            CurrentDir = CurrentDir + folder + @"\";
        }

        public static void BackDir()
        {
            var newPath = "";

            string[] pathSplit = CurrentDir.Split(@"\");
            for (int i = 0; i < pathSplit.Length - 2; i++)
            {
                newPath = newPath + pathSplit[i] + @"\";
            }
            CurrentDir = newPath;
        }

        public static string ReadFile(string fileName)
        {
            var fileContents = File.ReadAllText(GetPath() + fileName);
            return fileContents;
        }

        public static string GetPath()
        {
            return CurrentDir;
        }

        private static bool isRelative(string path)
        {
            bool relative = true;
            path += @"\";
            try
            {
                string[] pathSplit = path.Split(@"\");
                if (pathSplit[0] == "0:")
                {
                    relative = false;
                }
            }
            catch
            {
                BError.ParsingError();
            }
            return relative;
        }
    }
}
